# LivingStones/Dockerfile-django

FROM python:3.11.4

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install Node.js and npm
RUN apt-get update && \
    apt-get install -y nodejs npm

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir --index-url https://pypi.org/simple -r requirements.txt


# Copy project
COPY . /app/

# Change the working directory to /app/frontend
WORKDIR /app/frontend

# Install dependencies
RUN npm install

# Build the application
RUN npm run build

WORKDIR /app

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the port Daphne will run on
EXPOSE 8000

# Command to run the application
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "livingstones.asgi:application"]
