# LivingStones/Dockerfile-django-react

# LivingStones/Dockerfile-react

# Use the official Node.js image
FROM node:14-alpine AS build-stage

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json files
COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY frontend ./

# Change the working directory to /app/frontend
WORKDIR /app/frontend

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Serve the app
CMD ["npx", "serve", "-s", "build"]
