# LivingStones/docker-compose.yml

version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django
    image: django
    volumes:
      - ./media:/app/media/
      - ./db:/app/db/

    command: daphne -b 0.0.0.0 -p 8000 livingstones.asgi:application
    ports:
      - "8000:8000"

#  react:
#    build:
#      context: .
#      dockerfile: Dockerfile-react
#    container_name: react
#    ports:
#      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    volumes:
      - .:/app
      - ./media:/app/media/
      - ./db:/app/db/
    ports:
      - "80:80"
    depends_on:
      - django
#      - react
volumes:
  shared-media: