# LivingStones/Dockerfile-nginx

# LivingStones/Dockerfile-nginx

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY frontend/build /usr/share/nginx/html
COPY static /app/static
COPY media /app/media
