# LivingStones/docker-compose.yml

version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django
    image: django
    volumes:
      - shared-media:/app/media/
      - db-sqlite:/app/db/
      - db-migrations:/app/livingstonesapp/migrations/

    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py makemigrations livingstonesapp &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 livingstones.asgi:application"
    ports:
      - "8000:8000"

  #  react:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile-react
  #    container_name: react
  #    ports:
  #      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    volumes:
      - shared-media:/app/media/
      - db-sqlite:/app/db/
      - db-migrations:/app/livingstonesapp/migrations/

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - django
      - certbot

  certbot:
      image: certbot/certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"

volumes:
  shared-media:
  db-sqlite:
  db-migrations:

  certbot-etc:
  certbot-var: