# Generated by Django 5.0.6 on 2024-06-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_damage', models.IntegerField()),
                ('current_blood', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defend_mode', models.BooleanField(default=False)),
                ('boss_mode', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='livingstonesapp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='boss',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_of_game', to='livingstonesapp.gameplayer'),
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='livingstonesapp.game')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='livingstonesapp.gameplayer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacked_by', to='livingstonesapp.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_blood', models.IntegerField(default=100)),
                ('attack_power', models.IntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['game'], name='livingstone_game_id_c56649_idx'),
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['user'], name='livingstone_user_id_d3abbe_idx'),
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['created_at'], name='livingstone_created_00dc3a_idx'),
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['game'], name='livingstone_game_id_24108f_idx'),
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['attacker'], name='livingstone_attacke_b19727_idx'),
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['target'], name='livingstone_target__ddb092_idx'),
        ),
        migrations.AddIndex(
            model_name='attack',
            index=models.Index(fields=['timestamp'], name='livingstone_timesta_6087c7_idx'),
        ),
    ]
