# Generated by Django 5.0.6 on 2024-05-29 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_blood', models.IntegerField(default=100)),
                ('blood_level', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='npc_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='joined_games', to=settings.AUTH_USER_MODEL)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='livingstonesapp.npc')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='livingstonesapp.game')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacked_by', to='livingstonesapp.npc')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='livingstone_game_id_24108f_idx'), models.Index(fields=['attacker'], name='livingstone_attacke_b19727_idx'), models.Index(fields=['target'], name='livingstone_target__ddb092_idx'), models.Index(fields=['timestamp'], name='livingstone_timesta_6087c7_idx')],
            },
        ),
    ]
