# Generated by Django 5.0.6 on 2024-06-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstonesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gameplayer',
            name='livingstone_user_id_d3abbe_idx',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='user',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livingstonesapp.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['profile'], name='livingstone_profile_8929c8_idx'),
        ),
    ]
