# Generated by Django 5.0.6 on 2024-06-27 10:49

import livingstonesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingstonesapp', '0004_alter_gameplayer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='boss',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=livingstonesapp.models.unique_filename),
        ),
    ]
